package app.controllers;

import app.models.Professor;
import app.models.Student;
import app.models.User;
import app.repositories.ProfessorRepository;
import app.repositories.StudentRepository;
import app.repositories.UserRepository;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.Locale;

// This means that this class is a Controller
@Controller
// This means URL's start with / (after Application path)
@RequestMapping(path="/admin")
public class AdminController {
  // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private UserRepository userRepository;
  @Autowired
  private ProfessorRepository professorRepository;
  @Autowired
  private StudentRepository studentRepository;

  @GetMapping(path="/index")
  public String Index(Model model, HttpServletRequest request) {
    request.getSession().getAttribute("user");
    return "admin/index";
  }

  @GetMapping(path="/profile")
  public String Profile(HttpServletRequest request) {
    request.getSession().getAttribute("user");
    return "admin/profile";
  }

  @GetMapping(path="/students")
  public String Students(Model model, HttpServletRequest request) {
    Iterable<Student> students = studentRepository.findAll();
    model.addAttribute("students", students);
    return "admin/students";
  }

  @GetMapping(path="/professors")
  public String Professors(Model model) {
    Iterable<Professor> professors = professorRepository.findAll();
    model.addAttribute("professors", professors);
    return "/admin/professors";
  }
}